# File: .github/workflows/workflow.yml

name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to staging
    runs-on: [self-hosted, macOS, X64]

    steps:
      # Azure Login using Service Principal
      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      
