# File: .github/workflows/rock.yml

name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to staging
    runs-on: [self-hosted, mitalis-MacBook-Air]

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Azure Login using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Verify Azure login
      - name: Verify Azure login
        shell: pwsh
        run: |
          Write-Output "✅ Azure login successful"
          az account show
