name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  my_job:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v3
        with:
          # Azure client id
          client-id: ef918e69-be10-4267-9ac6-87000e61deb6
          # Azure client secret (store this in GitHub Secrets for security)
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          # Azure subscription id
          subscription-id: bc401604-b6cc-41b5-8eb3-22ccca3b29ff
          # Azure tenant id
          tenant-id: 36dff4507-8aab-483e-88d3-d7982c300017
          enable-AzPSSession: true
          environment: azurecloud
          allow-no-subscriptions: false
          audience: api://AzureADTokenExchange
          auth-type: SERVICE_PRINCIPAL
