# File: .github/workflows/test.yml

name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Azure Login using Service Principal
      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          client-id: 98df0580-39b3-4c8d-80ec-5143ae025113
          tenant-id: c85c100b-90ef-4945-b745-30b32789f421
          subscription-id: 669e5a53-2952-45fd-a198-1f4a3bdba879
          enable-AzPSSession: true
          environment: azurecloud
          allow-no-subscriptions: false
          audience: api://AzureADTokenExchange
          auth-type: SERVICE_PRINCIPAL
